version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./MqttBroker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      myNetwork:
        ipv4_address: 172.20.0.110


  ds1:
    build:
      context: Datasource
      dockerfile: dockerDatasource
    environment:
      DesIP: 172.20.0.110
      GrpcDest: 172.20.0.10
      Csv: config.csv
      id: 1
      sourceCount: 3
    networks:
      myNetwork:
        ipv4_address: 172.20.0.150
    depends_on:
      - mosquitto
  ds2:
    build:
      context: Datasource
      dockerfile: dockerDatasource
    environment:
      DesIP: 172.20.0.110
      GrpcDest: 172.20.0.10
      Csv: config.csv
      id: 2
      sourceCount: 3
    networks:
      myNetwork:
        ipv4_address: 172.20.0.151
    depends_on:
      - mosquitto
  ds3:
    build:
      context: Datasource
      dockerfile: dockerDatasource
    environment:
      DesIP: 172.20.0.110
      GrpcDest: 172.20.0.10
      Csv: config.csv
      id: 3
      sourceCount: 3
    networks:
      myNetwork:
        ipv4_address: 172.20.0.152
    depends_on:
      - mosquitto

  datastore:
    image: mbredel/datastore:krzyszton
    ports:
      - 8080:8080
      - 9090:9090
      - 6543:6543
    environment:
      - 'THRIFT_PORT:9090'
      - 'GRPC_PORT:8080'
      - 'PROTO_PORT:6543'
    networks:
      myNetwork:
        ipv4_address: 172.20.0.10


networks:
  myNetwork:
    name: myNetwork
    ipam:
      config:
        - subnet: 172.20.0.0/22
