version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./MqttBroker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      myNetwork:
        ipv4_address: 172.20.0.110


  ds1:
    build:
      context: Datasource
      dockerfile: dockerDatasource
    environment:
      DesIP: 172.20.0.110
      Csv: config.csv
      id: 1
      sourceCount: 2
    networks:
      myNetwork:
        ipv4_address: 172.20.0.150
    depends_on:
      - mosquitto
  ds2:
    build:
      context: Datasource
      dockerfile: dockerDatasource
    environment:
      DesIP: 172.20.0.110
      Csv: config.csv
      id: 2
      sourceCount: 2
    networks:
      myNetwork:
        ipv4_address: 172.20.0.151
    depends_on:
      - mosquitto


  datastore:
    image: mbredel/datastore:latest
    networks:
      myNetwork:
        ipv4_address: 172.20.0.10


networks:
  myNetwork:
    name: myNetwork
    ipam:
      config:
        - subnet: 172.20.0.0/22
